name: event_planner

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  fluttertoast: ^7.1.1
  intl: ^0.16.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.4
  cloud_firestore: ^0.14.0+2
  modal_progress_hud: ^0.1.3
  flutter_signin_button: ^1.1.0
  shared_preferences: ^0.5.12
  charts_flutter: ^0.9.0
  pie_chart: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: NotoSans
      fonts:
        - asset : assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset : assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset : assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset : assets/fonts/NotoSans-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf